services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:3333"
    environment:
      - PORT=3333
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ENV=production